language: node_js
node_js:
- '5.0'
after_success:
- npm run dist
deploy:
  provider: openshift
  user: $OPENSHIFT_USER
  password:
    secure: $OPENSHIFT_PASSWORD
  app: static
  domain: printeditor
  on:
    repo: ekougs/printable-doc-editor
    branch: master
